# Generated by Django 3.1.7 on 2021-02-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Genero', models.CharField(max_length=50)),
                ('Lanzamiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AutorCancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musiquita.autores')),
                ('NombreC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musiquita.cancion')),
            ],
        ),
    ]
